apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: taka-api
  labels:
    app: taka-api
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: taka-api
    spec:
      containers:
      - image: gcr.io/k8s-aksels/github-takaapp-api:v1.1
        name: taka-api-container
        imagePullPolicy: Always
        env:
        - name: GOOGLE_PLACES_API_KEY
          valueFrom:
            secretKeyRef:
              name: taka-api-secret
              key: GOOGLE_PLACES_API_KEY
        - name: ALGOLIA_SECRET
          valueFrom:
            secretKeyRef:
              name: taka-api-secret
              key: ALGOLIA_SECRET
        - name: ALGOLIA_APP_ID
          valueFrom:
            secretKeyRef:
              name: taka-api-secret
              key: ALGOLIA_APP_ID
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        ports:
        - containerPort: 1323
          name: taka-api-port
      restartPolicy: Always
